### ISSUE TITLE
Xpath over relation

### ISSUE THREAD

**Issue by TaraCampagne** [mendixlabs/time-series#10]
Hi!

Nice widget!
I would like to limit the visible period of the graph with a dateTime attribute in a object related to the graph object. I've tried this but it doesn't seem to be working?
I've tried the following path:
[Meetdatum>Dynamisch.MeetData_Meter/Klant.Meter/Klant.Meter_Gebouw/Klant.Gebouw/BegindatumDag]
Meter is the Graph object and MeetData the Point object in our model. Anyone knows what I'm doing wrong?

Further I was wondering if there will be an option to zoom in on a part of the graph in one of the next updates?

Thanks!

**Comment by djkwagala** [comment]
Thanks for bringing this to our notice. The zooming request is also noted. 
I'll create a sample project to test out the issue you are having and get back to you about it.

**Comment by Andries-Smit** [comment]
Time series widget will be discontinued. Time series is now implemented in a new bundel `Charts` https://appstore.home.mendix.com/link/app/105695/

Supporting both zoom and many other features. Please check if the new widget provides your need, else request a feature at https://github.com/mendixlabs/charts/issues
