### ISSUE TITLE
Please add an OnClick event for clicking on datapoints

### ISSUE THREAD

**Issue by mgroeneweg** [mendixlabs/time-series#11]
Hi,

I wanted to add an OnClick event to handle clicks on datapoints, only to notice that the internals of this widget are quite different.

Could you add the OnClick event please?

Thanks in advance,

Marcel

**Comment by djkwagala** [comment]
Thanks for noticing this. Its noted, we will get back to you.

**Comment by dannyroest** [comment]
We are currently working on a new chart series that will replace the timeseries widget which will include OnClick.

**Comment by Andries-Smit** [comment]
Time series widget will be discontinued. Time series is now implemented in a new bundel Charts https://appstore.home.mendix.com/link/app/105695/

Supporting on click events and many other features. Please check if the new widget provides your need, else request a feature at https://github.com/mendixlabs/charts/issues
